# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # CSRF, forms, sessions rade samo uz validnu session konfiguraciju
    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: lax

    # Ako koristiš form builder i CSRF
    csrf_protection: true
    form: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['en']
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
